# Generated by Django 5.0.3 on 2024-10-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_formapplicant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventproject',
            table='EventProject',
        ),
    ]
