# Generated by Django 5.0.3 on 2024-11-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_eventproject_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='time',
            field=models.TextField(default='10:00'),
            preserve_default=False,
        ),
    ]
